### ISSUE TITLE
[Documento de Requisitos] Adicionar os requisitos funcionais

### ISSUE THREAD

**Issue by esterchamps** [larissarsilva/EngenhariaDeSoftware#9]
Todos adicionados com o status de editor no documento compartilhado.
*IMPORTANTE:* Após edição, salvar o arquivo no repositório.

Casos:
- [x] Cancelar Candidatura
- [x] Cadastrar no SisMonitoria
- [x] Realizar Inscrição para Monitor
- [x] Consultar Edital
- [x] Disponibilizar Edital
- [x] Ofertar Disciplina
- [x] Aprovar Monitor
- [x] Consultar Candidatura
- [x] Consultar Sala
- [x] Classificar Monitor
- [x] Preencher Ata de Presença
- [x] Disponibilizar Ata de Presença
- [x] Consultar Ata de Presença
- [x] Solicitar Desligamento da Monitoria
- [x] Modificar Candidatura
- [x] Desligar Monitor
- [x] Solicitar Sala para Monitoria
- [x] Disponibilizar Sala para Monitoria
- [x] Consultar Certificado
- [x] Gerar Certificado
- [x] Enviar Lista de Classificados
- [x] Enviar Notificações

**Comment by pedro-oliveira446** [comment]
Ação "Solicitar sala para monitoria" descrita no documento de requisitos.
